services:
  - type: web
    name: school-scheduler
    runtime: python
    region: ohio
    plan: free
    buildCommand: cd backend && ./build.sh
    startCommand: cd backend && gunicorn -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: school-scheduler-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: PORT
        value: 10000
      - key: DJANGO_SETTINGS_MODULE
        value: scheduler_config.settings
    healthCheckPath: /admin/
    autoDeploy: false

databases:
  - name: school-scheduler-db
    databaseName: school_scheduler
    user: school_scheduler
    plan: free 