services:
  - type: web
    name: school-scheduler
    runtime: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt && cd backend && ./build.sh
    startCommand: cd backend && gunicorn scheduler_config.wsgi:application --bind=0.0.0.0:$PORT --workers 4 --log-file logs/gunicorn.log --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: school-scheduler-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 10000
      - key: DJANGO_SETTINGS_MODULE
        value: scheduler_config.settings
    healthCheckPath: /admin/
    autoDeploy: true

databases:
  - name: school-scheduler-db
    databaseName: school_scheduler
    user: school_scheduler
    plan: free 