services:
  - type: web
    name: school-scheduler-django
    runtime: python
    region: ohio
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd backend
      chmod +x build.sh
      ./build.sh
    startCommand: gunicorn app:app --bind=0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: school-scheduler-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: scheduler_config.settings
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/backend
      - key: PORT
        value: 10000
    healthCheckPath: /admin/
    autoDeploy: true

databases:
  - name: school-scheduler-db
    databaseName: school_scheduler
    user: school_scheduler
    plan: free 