services:
  - type: web
    name: school-scheduler
    env: python
    buildCommand: cd backend && ./build.sh
    startCommand: gunicorn wsgi:app --bind=0.0.0.0:$PORT --log-file backend/logs/gunicorn.log --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: school-scheduler-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 8000
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: scheduler_config.settings

databases:
  - name: school-scheduler-db
    databaseName: school_scheduler
    user: school_scheduler
    plan: free 