services:
  - type: web
    name: school-scheduler
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn scheduler_config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: school-scheduler-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHONPATH
        value: .

databases:
  - name: school-scheduler-db
    databaseName: school_scheduler
    user: school_scheduler
    plan: free 