# Generated by Django 4.2.20 on 2025-03-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('allow_teacher_multiple_rooms', models.BooleanField(default=False, help_text='Allow teachers to be scheduled in different rooms throughout the day')),
                ('max_consecutive_periods', models.IntegerField(default=3, help_text='Maximum number of consecutive periods a teacher can teach')),
                ('separate_grade_levels', models.BooleanField(default=True, help_text='Keep different grade levels in separate periods when possible')),
                ('stagger_grade_level_lunches', models.BooleanField(default=True, help_text='Ensure different grade levels have lunch at different times')),
                ('require_subject_specific_rooms', models.BooleanField(default=True, help_text='Require specific subjects to be taught in specific rooms')),
                ('schedule_electives_together', models.BooleanField(default=True, help_text='Schedule elective courses in the same periods')),
                ('elective_grade_levels', models.CharField(default='8', help_text='Comma-separated list of grade levels that have electives', max_length=50)),
                ('preferred_core_subject_periods', models.CharField(blank=True, help_text='Comma-separated list of preferred periods for core subjects', max_length=100)),
                ('custom_rules', models.JSONField(default=dict, help_text='Additional custom scheduling rules in JSON format')),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('REQUIRED', 'Required'), ('ELECTIVE', 'Elective')], default='REQUIRED', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('QUARTER', 'Quarter'), ('TRIMESTER', 'Trimester'), ('YEAR', 'Full Year')], default='TRIMESTER', max_length=10),
        ),
    ]
