# Generated by Django 4.2.20 on 2025-03-13 02:08

from django.db import migrations

def update_required_to_core(apps, schema_editor):
    Course = apps.get_model('scheduler', 'Course')
    Course.objects.filter(course_type='REQUIRED').update(course_type='CORE')

def revert_core_to_required(apps, schema_editor):
    Course = apps.get_model('scheduler', 'Course')
    Course.objects.filter(course_type='CORE').update(course_type='REQUIRED')

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_update_course_type_choices'),
    ]

    operations = [
        migrations.RunPython(
            update_required_to_core,
            revert_core_to_required
        ),
    ]
