# Generated by Django 4.2.20 on 2025-03-13 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_update_required_to_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_students',
            field=models.IntegerField(blank=True, help_text='Maximum number of students allowed in this section (optional, defaults to course max_students_per_section)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
