# Generated by Django 4.2.20 on 2025-03-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_section_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='trimester',
            field=models.IntegerField(blank=True, choices=[(1, 'Trimester 1'), (2, 'Trimester 2'), (3, 'Trimester 3')], db_index=True, help_text='Which trimester this section is scheduled for (required for trimester courses)', null=True),
        ),
    ]
