# Generated by Django 4.2.20 on 2025-03-11 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_schedulingconfiguration_separate_siblings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Family name or identifier for this sibling group', max_length=100)),
                ('students', models.ManyToManyField(help_text='Students who are siblings in this family', limit_choices_to={'role': 'STUDENT'}, related_name='sibling_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sibling Group',
                'verbose_name_plural': 'Sibling Groups',
            },
        ),
        migrations.DeleteModel(
            name='SiblingRelationship',
        ),
    ]
