# Generated by Django 4.2.20 on 2025-03-13 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_section_trimester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_student_count',
            field=models.IntegerField(blank=True, help_text='Required number of students (used with Exact, Minimum, or Maximum requirement types)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='course',
            name='student_count_requirement_type',
            field=models.CharField(choices=[('EXACT', 'Exact Number'), ('MIN', 'Minimum Number'), ('MAX', 'Maximum Number'), ('FULL', 'Full Grade (Default)')], default='FULL', help_text='How to enforce student count requirements for this course', max_length=10),
        ),
    ]
