# Generated by Django 4.2.20 on 2025-03-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_course_required_student_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the course group (e.g., 'Theatre and Coding Combinations')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of why these courses are mutually exclusive')),
            ],
            options={
                'verbose_name': 'Course Group',
                'verbose_name_plural': 'Course Groups',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='exclusivity_group',
            field=models.ForeignKey(blank=True, help_text='Group of mutually exclusive courses this course belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='scheduler.coursegroup'),
        ),
    ]
