# Generated by Django 4.2.20 on 2025-03-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_coursegroup_course_exclusivity_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
        migrations.DeleteModel(
            name='SiblingGroup',
        ),
        migrations.DeleteModel(
            name='StudentGroup',
        ),
    ]
