# Generated by Django 4.2.20 on 2025-03-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_studentgroup_students_delete_siblinggroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('LANGUAGE', 'Language')], db_index=True, default='CORE', help_text='Type of course (CORE or ELECTIVE)', max_length=10),
        ),
        migrations.CreateModel(
            name='LanguageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the language group (e.g., '6th Grade Languages')", max_length=100)),
                ('grade_level', models.IntegerField(help_text='Grade level for this language group')),
                ('courses', models.ManyToManyField(help_text='Language courses in this group', limit_choices_to={'course_type': 'LANGUAGE'}, related_name='language_group', to='scheduler.course')),
                ('period', models.ForeignKey(help_text='Period when these language courses are offered', on_delete=django.db.models.deletion.CASCADE, to='scheduler.period')),
            ],
            options={
                'verbose_name': 'Language Group',
                'verbose_name_plural': 'Language Groups',
                'unique_together': {('period', 'grade_level')},
            },
        ),
    ]
