# Generated by Django 4.2.20 on 2025-03-12 02:00

from django.db import migrations

def populate_user_ids(apps, schema_editor):
    User = apps.get_model('scheduler', 'User')
    for i, user in enumerate(User.objects.all()):
        prefix = 'S' if user.role == 'student' else 'T' if user.role == 'teacher' else 'A'
        user.user_id = f"{prefix}LEGACY{i+1}"
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_add_user_id_nullable'),
    ]

    operations = [
        migrations.RunPython(populate_user_ids),
    ]
