# Generated by Django 4.2.20 on 2025-03-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_populate_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='LEGACY', help_text='Unique identifier for all users', max_length=50, unique=True),
        ),
    ]
