# Generated by Django 4.2.20 on 2025-03-12 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_make_user_id_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, help_text='Simple course code (e.g., English7)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students_per_section',
            field=models.IntegerField(default=30, help_text='Maximum number of students per section'),
        ),
        migrations.AddField(
            model_name='course',
            name='num_sections',
            field=models.IntegerField(default=1, help_text='Number of sections to be offered for this course'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(help_text='Section number (e.g., 1, 2, 3)')),
                ('name', models.CharField(help_text='Generated section name (e.g., English7-1)', max_length=150, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduler.course')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='scheduler.period')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='scheduler.room')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_sections', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'section_number'],
                'unique_together': {('course', 'section_number')},
            },
        ),
    ]
