# Generated by Django 4.2.20 on 2025-03-12 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_remove_course_max_students_remove_course_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students enrolled in this course (to be assigned to sections by the scheduler)', limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students assigned to this section by the scheduler', limit_choices_to={'role': 'STUDENT'}, related_name='assigned_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
