# Generated by Django 4.2.20 on 2025-03-12 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_coursetypeconfiguration_electiveconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students registered for this course (to be assigned to sections by the scheduler)', limit_choices_to={'role': 'STUDENT'}, related_name='registered_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
