# Generated by Django 4.2.20 on 2025-03-11 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_siblinggroup_delete_siblingrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSeparationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this separation group (e.g., 'Behavior Group A' or 'Conflict Group 1')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional notes about why these students should be separated')),
                ('priority', models.IntegerField(default=1, help_text='Higher priority (1-5) separation groups will be considered first in scheduling')),
                ('students', models.ManyToManyField(help_text='Students who should not be scheduled in the same period', limit_choices_to={'role': 'STUDENT'}, related_name='separation_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Separation Group',
                'verbose_name_plural': 'Student Separation Groups',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
