# Generated by Django 4.2.20 on 2025-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_studentseparationgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='respect_separation_groups',
            field=models.BooleanField(default=True, help_text='Avoid scheduling students from separation groups in the same period'),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='separation_group_priority',
            field=models.IntegerField(choices=[(5, 'Highest Priority - Must be separated'), (4, 'High Priority'), (3, 'Medium Priority'), (2, 'Low Priority'), (1, 'Lowest Priority - Try to separate if possible')], default=3, help_text='Default priority level for separation groups (5 = highest priority, must be separated; 1 = lowest priority, separate if possible)'),
        ),
        migrations.AlterField(
            model_name='studentseparationgroup',
            name='priority',
            field=models.IntegerField(choices=[(5, 'Highest Priority - Must be separated'), (4, 'High Priority'), (3, 'Medium Priority'), (2, 'Low Priority'), (1, 'Lowest Priority - Try to separate if possible')], default=3, help_text='Priority level for separation (5 = highest priority, must be separated; 1 = lowest priority, separate if possible)'),
        ),
    ]
